// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistencia.Inventario.Models;

public partial class Usuario
{
    public int IdUser { get; set; }

    public string UserName { get; set; }

    public string Correo { get; set; }

    public string PasswordHash { get; set; }

    public string Rol { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiryTime { get; set; }

    public DateTime? FechaRegistro { get; set; }
}